apiVersion: v1
kind: Service
metadata:
  name: leaderQuartz-service
spec:
  ports:
    - protocol: TCP
      port: 8989           # Port exposed inside the cluster
      targetPort: 80       # Port where the application is listening on inside the pod
  selector:
    app: leaderQuartz
  type: LoadBalancer
status:
  loadBalancer: {}